### PR TITLE
chore: Standardize CI with other projects

### PR DESCRIPTION
**Pull request by ghislainbourgeois**

### CODE REVIEW

**Comment by ghislainbourgeois** [comment]
@gab-arrobo , the onf-bot does not seem to notify you for this project.

**Comment by gab-arrobo** [comment]
> @gab-arrobo , the onf-bot does not seem to notify you for this project.

Thanks for letting me know. You are correct, I did not get any notification

**Comment by gab-arrobo** [comment]
Hi @ghislainbourgeois, FYI, I just opened 3 PRs in AMF, UDM, AUSF to use the `util` repo instead of this repo. I still need to open one PR in the gnbsim repo to fully remove the dependency from this repo.

**Comment by gab-arrobo** [comment]
@ghislainbourgeois, BTW, it would be great if you can help opening some PRs to replace some of the repos I indicated in the TST notes and use the `util` repo instead.

**Comment by ghislainbourgeois** [comment]
@gab-arrobo I started creating some PRs also relating to other deps. Feel free to close those PRs when your other PRs are merged.

**Pull request closed without merging**
